-- Roofing Advisor conversations, assessments and events.
--
-- The advisor writes here from the server with the service role. Enum values
-- mirror src/lib/roofing-advisor/store/types.ts (conversation status),
-- src/lib/roofing-advisor/types.ts (message role) and
-- src/lib/roofing-advisor/events.ts (event type); change both together.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type public.advisor_conversation_status as enum (
  'active', 'handoff', 'complete', 'closed'
);

create type public.advisor_message_role as enum ('user', 'advisor');

create type public.advisor_event_type as enum (
  'LEAD_CREATED',
  'ASSESSMENT_COMPLETED',
  'ESTIMATE_GENERATED',
  'PHOTO_UPLOADED',
  'HUMAN_REQUESTED',
  'CONTACT_SUBMITTED'
);

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- One row per chat. The id is generated by the browser when the chat opens.
create table public.advisor_conversations (
  id uuid primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status public.advisor_conversation_status not null default 'active',
  -- The advisor's stage: greeting, understanding, qualifying, estimating,
  -- contact, complete, human_handoff or closed.
  stage text not null default 'greeting',
  -- Set once, by upsert_advisor_lead. Unique: one lead per conversation.
  lead_id uuid unique references public.leads (id) on delete set null
);

create index advisor_conversations_updated_at_idx
  on public.advisor_conversations (updated_at desc);

create table public.advisor_messages (
  id uuid primary key,
  conversation_id uuid not null
    references public.advisor_conversations (id) on delete cascade,
  role public.advisor_message_role not null,
  content text not null,
  -- The goal behind an advisor question, and photo attachments.
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index advisor_messages_conversation_id_created_at_idx
  on public.advisor_messages (conversation_id, created_at);

-- The latest structured assessment for each conversation.
create table public.advisor_assessments (
  conversation_id uuid primary key
    references public.advisor_conversations (id) on delete cascade,
  assessment_json jsonb not null,
  confidence_json jsonb not null default '{}'::jsonb,
  estimate_json jsonb,
  -- Internal lead quality. Never shown to the homeowner.
  completeness_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- What happened, for automation to pick up later.
create table public.advisor_events (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null
    references public.advisor_conversations (id) on delete cascade,
  lead_id uuid references public.leads (id) on delete set null,
  event_type public.advisor_event_type not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index advisor_events_conversation_id_created_at_idx
  on public.advisor_events (conversation_id, created_at);
create index advisor_events_event_type_created_at_idx
  on public.advisor_events (event_type, created_at);

-- ---------------------------------------------------------------------------
-- Keeping the lead's conversation complete
-- ---------------------------------------------------------------------------

-- Once a conversation has a lead, new advisor messages also land in
-- lead_messages, so the admin sees the whole conversation.
create function public.mirror_advisor_message()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_lead_id uuid;
begin
  select lead_id into v_lead_id
  from public.advisor_conversations
  where id = new.conversation_id;

  if v_lead_id is not null then
    insert into public.lead_messages (lead_id, direction, channel, message, created_at)
    values (
      v_lead_id,
      (case when new.role = 'user' then 'inbound' else 'outbound' end)::public.message_direction,
      (case when new.role = 'user' then 'customer' else 'ai' end)::public.message_channel,
      coalesce(nullif(new.content, ''), '[Shared a photo]'),
      new.created_at
    );
  end if;
  return new;
end;
$$;

create trigger advisor_messages_mirror_to_lead
  after insert on public.advisor_messages
  for each row execute function public.mirror_advisor_message();

-- ---------------------------------------------------------------------------
-- Lead creation
-- ---------------------------------------------------------------------------

-- Creates the conversation's lead the first time, and keeps it current after
-- that. Locking the conversation row makes this idempotent: two requests for
-- the same conversation can never create two leads. Returns
-- {"lead_id": uuid, "created": boolean}.
create function public.upsert_advisor_lead(p_conversation_id uuid, p_lead jsonb)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_lead_id uuid;
  v_created boolean := false;
  v_row public.leads;
begin
  select lead_id into v_lead_id
  from public.advisor_conversations
  where id = p_conversation_id
  for update;

  if not found then
    raise exception 'Advisor conversation % not found', p_conversation_id;
  end if;

  v_row := jsonb_populate_record(null::public.leads, p_lead);

  if v_lead_id is null then
    insert into public.leads (
      name, email, phone, address, city, state, zip_code, issue_type,
      roof_age, roof_type, urgency, description, preferred_contact_method,
      preferred_time
    )
    values (
      v_row.name, v_row.email, v_row.phone, v_row.address, v_row.city,
      v_row.state, v_row.zip_code, v_row.issue_type, v_row.roof_age,
      v_row.roof_type, v_row.urgency, v_row.description,
      v_row.preferred_contact_method, v_row.preferred_time
    )
    returning id into v_lead_id;
    v_created := true;

    update public.advisor_conversations
    set lead_id = v_lead_id, updated_at = now()
    where id = p_conversation_id;

    -- The conversation so far becomes the lead's message history.
    insert into public.lead_messages (lead_id, direction, channel, message, created_at)
    select
      v_lead_id,
      (case when m.role = 'user' then 'inbound' else 'outbound' end)::public.message_direction,
      (case when m.role = 'user' then 'customer' else 'ai' end)::public.message_channel,
      coalesce(nullif(m.content, ''), '[Shared a photo]'),
      m.created_at
    from public.advisor_messages m
    where m.conversation_id = p_conversation_id
    order by m.created_at;

    -- Photos shared before the lead existed.
    insert into public.lead_photos (lead_id, storage_path, created_at)
    select v_lead_id, attachment ->> 'storage_path', m.created_at
    from public.advisor_messages m
    cross join lateral jsonb_array_elements(
      coalesce(m.metadata -> 'attachments', '[]'::jsonb)
    ) as attachment
    where m.conversation_id = p_conversation_id
      and attachment ->> 'storage_path' is not null;

    insert into public.lead_events (lead_id, event_type, metadata)
    values (
      v_lead_id,
      'lead_created',
      jsonb_build_object('source', 'roofing_advisor', 'conversation_id', p_conversation_id)
    );
  else
    -- Later turns keep the lead current. Status and automation belong to the team.
    update public.leads
    set
      name = v_row.name,
      email = coalesce(v_row.email, email),
      phone = coalesce(v_row.phone, phone),
      address = coalesce(v_row.address, address),
      city = coalesce(v_row.city, city),
      state = coalesce(v_row.state, state),
      zip_code = coalesce(v_row.zip_code, zip_code),
      issue_type = v_row.issue_type,
      roof_age = coalesce(v_row.roof_age, roof_age),
      roof_type = coalesce(v_row.roof_type, roof_type),
      urgency = coalesce(v_row.urgency, urgency),
      description = coalesce(v_row.description, description),
      preferred_contact_method = coalesce(v_row.preferred_contact_method, preferred_contact_method),
      preferred_time = coalesce(v_row.preferred_time, preferred_time)
    where id = v_lead_id;
  end if;

  return jsonb_build_object('lead_id', v_lead_id, 'created', v_created);
end;
$$;

-- Only the server (service role) creates leads.
revoke execute on function public.upsert_advisor_lead(uuid, jsonb) from public, anon, authenticated;
grant execute on function public.upsert_advisor_lead(uuid, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- Photo storage
-- ---------------------------------------------------------------------------

-- Private bucket. The server uploads with the service role; the admin reads
-- through signed URLs once it's connected.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'advisor-photos',
  'advisor-photos',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Same as the initial schema: on, with no policies, so only the service role
-- can read or write these tables.
-- ---------------------------------------------------------------------------

alter table public.advisor_conversations enable row level security;
alter table public.advisor_messages enable row level security;
alter table public.advisor_assessments enable row level security;
alter table public.advisor_events enable row level security;
